FROM golang:1.22 AS build
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 CGOOS=linux GOARCH=amd64 go build -o serviceB main.go

FROM scratch
WORKDIR /app
COPY  --from=build /app/serviceB .
ENTRYPOINT [ "./serviceB" ]
EXPOSE 8081